### ISSUE TITLE
Tracking Roadmap

### ISSUE THREAD

**Issue by circuitfox** [circuitfox/vitae-net#128]
We can use this issue to track what we have left to complete in the project. I'll edit this as we add things in and they get finished.

#### MAR

- [x] Database Migrations & Updated ERD (#113, #127, #84)
- [x] Models & Relationships (#114)
- [x] Controllers (#115)
- [x] Views (#116)
- [x] Editing (#163)

#### Assessments

- [x] Migrations & ERD (#154)
- [x] Factories (#154)
- [x] Controller (#155)
- [x] Views (#156)

#### Javascript

- [x] Patient QR Parser (#112)
- [x] Patient & Medication Barcode Parser (#88)

#### View Bugs

- [x] Edit View Dropdowns (#119)
- [x] QR Formatter Layout (#121)
- [x] Collapsing Navbar (#96)

#### Misc.

- [x] Embed order/lab files (#131)
- [ ] Student UX (#161)

### Testing

- [ ] Javascript (#37)

### Documentation

- [ ] Update README (#95)
- [ ] Barcode Documentation
- [ ] Code Documentation

### Infrastructure

- [x] Fix travis deployment
- [x] Get subdomain (vitaenet.aurora.edu)
- [x] Get SSL certificate

### Barcoding

- [x] Encoding (#130)
- [x] Format (#130, #137)
- [ ] Generation Documentation
- [x] Formatting Tools (#137)
- [x] Parsing
- [x] Storing (#137, #138)
- [x] Generating (#137)
